[package]
name = "tapirus-ffi"
version = "1.0.1"
edition = "2024"
authors = ["Ahmad Faiz <faiz@tapirusdb.com>"]
license = "BUSL-1.1"
description = "C Foreign Function Interface (FFI) bindings for TapirusDB"
repository = "https://github.com/tapiruslab/TapirusDB"

[lib]
name = "tapirus"
crate-type = ["cdylib", "staticlib"]

[dependencies]
tapirus = { path = "../.." }
